import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import NavMenu from "../components/NavMenu";
import Layout from "../components/Layout";
import { getAmbassadorer, getFrontPageAcf } from "../lib/api";
import VideoCard from "../components/videoCard";
import { Container } from "react-bootstrap";
import { useState } from "react";

export default function Home({ ambassadorer, acf }) {
    return (
        <>
            <div>
                <Head>
                    <title>Stand Bli rørlegger</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
            <NavMenu />

            <div className="__inner bg">
                <div className="card-grid container">
                    {ambassadorer.map(({ node }) => {
                        return <VideoCard key={node.id} item={node} />;
                    })}
                </div>
            </div>

            <Container>
                <h2>{acf.frontpageAcf.title}</h2>
                <div dangerouslySetInnerHTML={{__html: acf.frontpageAcf.content}} />
                <p>{acf.frontpageAcf.eventTitle}</p>
                {acf.frontpageAcf.events.map((i) => {
                    return (
                        <p key={i.event} className="eventItem">{i.event}</p>
                    )
                })}
            </Container>

            <Footer />
        </>
    );
}

export async function getStaticProps() {
    const ambassadorer = await getAmbassadorer();
    const acf = await getFrontPageAcf();

    return {
        props: {
            ambassadorer,
            acf
        }
    };
}
